### PR TITLE
Apply heading styles to heading classes

### PR DESCRIPTION
**Pull request by restlessbit**
Adds heading styles to heading classes, like `.h1`, `.h2`, `.h3`, etc.

screen shot 2016-07-08 at 10 50 24 am

/cc @underdogio/engineering

### CODE REVIEW

**Comment by brettlangdon** [comment]
but, this won't actually apply the correct font sizing will it?

**Comment by restlessbit** [comment]
They do not :'( One sec...

**Comment by restlessbit** [comment]
Fixed

**Comment by brettlangdon** [comment]
lgtm

**Pull request merged**
