### PR TITLE
Widen menu icon

### PR DESCRIPTION
**Pull request by restlessbit**
Widens the menu icon from this:

before

To this:

after

/cc @underdogio/engineering

### CODE REVIEW

**Comment by brettlangdon** [comment]
I see... I see...

**Comment by brettlangdon** [comment]
Any reason?

**Comment by restlessbit** [comment]
square icon ugly

**Comment by brettlangdon** [comment]
Looks fine to me, just cc'ing @cmuir so he knows of the change.

**Comment by cmuir** [comment]
Bam.

**Pull request merged**
