### PR TITLE
Create a 404 Not Found template

### LINKED ISSUE #168: Add a 404 Not Found template

### PR DESCRIPTION
**Pull request by restlessbit**
Closes #168 

Adds a 'Not Found' template that is rendered when a non-existing section or route is requested. 

Also breaks out the header and table of contents into partials so that they can be used in multiple layouts.

screen shot 2016-06-14 at 5 59 46 pm

/cc @underdogio/engineering

### CODE REVIEW

**Comment by brettlangdon** [comment]
We don't want to keep the side nav bar for this page?

**Comment by restlessbit** [comment]
Actually, we do 😃

**Comment by restlessbit** [comment]
I added the sidebar to the not-found template:

screen shot 2016-06-16 at 5 53 43 pm

**Comment by brettlangdon** [comment]
Can we change the link text to `Go home, you're drunk`?

**Comment by brettlangdon** [comment]
lgtm

**Pull request merged**
