### PR TITLE
Update nav-list item spacing to 18px

### PR DESCRIPTION
**Pull request by restlessbit**
Tweakin' yo

/cc @underdogio/engineering

### CODE REVIEW

**Comment by brettlangdon** [comment]
This is what we want across everything?

Is there some more context here? before/after, mock from chris? I do not recall this discussion.

**Comment by restlessbit** [comment]
Yeah; this is coming from Zeplin.

screen shot 2016-07-12 at 1 25 14 pm

**Comment by brettlangdon** [comment]
Thanks.

Ugh, I wish there was a permalink for comments so you could leave them in here.

For things from Zeplin, mind just sharing the screen you are working from? e.g. https://app.zeplin.io/project.html#pid=5783eecf83b2efb85b3757e7&sid=5783ef462160e20209b3cd30

Then I can go hunt the comment down.

(This isn't a I don't trust that you read it properly, just a good verification/trail to leave in the PR).

**Comment by brettlangdon** [comment]
lgtm

**Comment by restlessbit** [comment]
Ahh, I totally forgot about the web app

**Pull request merged**
