### PR TITLE
Make links bold

### PR DESCRIPTION
**Pull request by restlessbit**
*Before*

screen shot 2016-07-12 at 11 26 10 am

*After*

screen shot 2016-07-12 at 11 24 18 am

/cc @underdogio/engineering

### CODE REVIEW

**Comment by brettlangdon** [comment]
This is for all links on the site right?

How does this effect the header/dropdowns/sidebar nav/etc?

/cc @cmuir for quick approval

**Comment by restlessbit** [comment]
Yes, and they all have the same `400` font weight as before.

**Comment by brettlangdon** [comment]
okie dokie, lgtm

**Comment by cmuir** [comment]
Did we make these semi-bold or bold? Think semi-bold is 600, and bold is 700. I like 600 bc it gives us some room to use 700 for headers/other more prominent text. That's what I used in the mocks.

**Pull request merged**
