### PR TITLE
Add component for linking to case studies

### PR DESCRIPTION
**Pull request by restlessbit**
Adds a `case-study-intro` component for linking to case studies.

*Static image from [Zeplin](https://zpl.io/Z21jJQx)*

screen shot 2016-08-15 at 3 58 24 pm

*Normal view*

normal

*Collapsed*

collapsed

*Hover*

untitled gif

/cc @underdogio/engineering @cmuir

### CODE REVIEW

**Comment by cmuir** [comment]
Looks like the dark blue bg is a different color than the mock. Should be #11344F.

How did we decide on the dimensions of the images and the corresponding text block? The mock had the images a bit more square (~600px by 400px).

If the hover state causes the image to zoom/blur a little, I'd love to see a live preview of that.

**Comment by restlessbit** [comment]
The background color being set here is a default color; the background color can be overridden for different case studies inline.

The resolution of the mock is different from the resolution of my monitor when the screenshot was taken, so the size of the image is going to differ. The size of the text block is set to be `300px`, and the image is set to stretch to fill the remaining width of the container.

For the hover state, we could use a slightly larger image to offset any blurring that may occur on zoom. If that's not possible, then I can remove the zoom effect.

**Comment by restlessbit** [comment]
Just refactored a variable; no visual changes.

**Comment by brettlangdon** [comment]
@restlessbit do you have a preview/example of the hover states with a real image?

Would love to see what it look/feels like with a real example like Managed by Q images, etc.

**Comment by brettlangdon** [comment]
But otherwise, the code lgtm

**Comment by restlessbit** [comment]
I removed the image zoom effect because it was ghastly, and I increased the width of the text portion a bit:

screen shot 2016-08-16 at 3 59 40 pm

I think it's looking taaaaaastyyyyyyyyy

**Comment by brettlangdon** [comment]
lgtm

**Comment by restlessbit** [comment]
@cmuir It's lookin tasty right?

**Comment by cmuir** [comment]
Heck yeah

**Pull request merged**
