### PR TITLE
Allow header content to be resized

### PR DESCRIPTION
**Pull request by restlessbit**
Allows the content within `.header` to be constrained to a max width by introducing a new element, `.header__content`. The max width can be adjusted by setting a value for the `$header-max-width` variable.

/cc @underdogio/engineering

### CODE REVIEW

**Comment by brettlangdon** [comment]
screenshot? what does this affect?

**Comment by brettlangdon** [comment]
ah, we have to update downstream apps to use `.header__content` now?

**Comment by restlessbit** [comment]
Yeah, this is a breaking change :'(  

There aren't any visual changes, but this will allow other projects to set the max width on a fixed header while keeping the white background of the header at full width.  

*Before (max-width set on .header)*:

screen shot 2016-07-18 at 6 15 53 pm

*After (with .header__content)*:

screen shot 2016-07-18 at 6 14 51 pm

**Comment by brettlangdon** [comment]
Is there any way to do it without it being a breaking change? e.g. make `.header__content` optional? What happens if you keep the original properties for `.header`? I assume bad things?

**Comment by restlessbit** [comment]
That's a good idea. Bad things to happen, but nothing that can't be fixed with a bit more CSS.

Also, I just realized that I forgot to update the documentation for the header component. 😵 👊

**Comment by restlessbit** [comment]
I made the `.header__content` element optional and updated the documentation accordingly.

**Comment by brettlangdon** [comment]
nice :+1:

**Pull request merged**
