### PR TITLE
Add cell element to well block

### PR DESCRIPTION
**Pull request by restlessbit**
Adds styles for this thing:

screen shot 2016-09-13 at 11 12 42 am

/cc @underdogio/engineering

### CODE REVIEW

**Comment by brettlangdon** [comment]
What is this for?

**Comment by restlessbit** [comment]
Onboarding

**Comment by brettlangdon** [comment]
ok... that was helpful... where are they being used in onboarding? ;P

**Comment by restlessbit** [comment]
screen shot 2016-09-13 at 2 15 40 pm

**Comment by brettlangdon** [comment]
lgtm

**Pull request merged**
