### PR TITLE
Create Sign Up form template

### PR DESCRIPTION
**Pull request by restlessbit**
This PR introduces the "Templates" category into the styleguide, which will be used to keep track of different page templates used in our apps and services. This will also come in handy for testing how a style change will affect multiple apps at once.

The first template is the "Sign Up Form" template:

screen shot 2016-07-18 at 1 22 08 pm

/cc @underdogio/engineering

### CODE REVIEW

**Comment by brettlangdon** [comment]
So, we have to maintain this component/template in here, as well as across multiple applications?

**Comment by restlessbit** [comment]
Yup. Doing that will prevent us from deploying a change that works for one service but not for another. It also gives an easy way to test how multiple components will work together.

**Comment by brettlangdon** [comment]
Sounds like a lot of work...

**Comment by restlessbit** [comment]
It's mostly copy + pasta. And I think having a single place where we can take a quick peek to make sure a change doesn't break any of our apps makes the work worth it.

**Comment by brettlangdon** [comment]
But, doesn't gemini offer us that as well?

**Comment by brettlangdon** [comment]
we could always introduce visual diff testing into our pipeline as well

**Comment by restlessbit** [comment]
I suppose we could.

**Comment by brettlangdon** [comment]
we also do have gemini setup for some of the projects, maybe we need to figure out a better workflow for testing styleguide changes across apps.

I'd basically prefer to find a good scalable solution that is also easy for us to remember/implement. Adding this one form to the styelguide isn't that big of a deal, but when it starts to get bloated with other components, and then we have to cascade update any of the forms across apps, etc etc. It could become a problem.

It would probably be a different story if we were storing common visual React components in here or something, where we could import/reuse the forms across projects, but that probably isn't the best for us right now.

**Comment by cmuir** [comment]
Is that placeholder text #dcdcdc like it is in the mocks?

**Comment by brettlangdon** [comment]
@cmuir sorry, might not be the best place for that comment, in this PR we aren't re-working/updating any of the form styles. I assume that is a change that will come later.

**Comment by cmuir** [comment]
Ah, good to know. Carry on.

**Comment by brettlangdon** [comment]
@restlessbit still thinking on this some more, lets leave open for now, can come back later. It isn't blocking you right?

**Comment by restlessbit** [comment]
@brettlangdon No it's not blocking me.

@cmuir Unfortunately you can't change placeholder text styling :'(

**Comment by brettlangdon** [comment]
I had a thought here this weekend.

Maybe it is worth just having a generic "examples" section, like, an example of a two column form, and a single column form, of a "landing page layout".

Some examples of "composed" components/layouts but keep it really loose and generic so that we don't have to try and maintain things in multiple places. It is more of a "want to do a form? here are two options to get you started" type of deal.

**Comment by brettlangdon** [comment]
Closing this for now since it has sat for awhile.

**Pull request closed without merging**
