### PR TITLE
Add colors section to styleguide

### LINKED ISSUE #173: Add colors to styleguide
It would be super helpful if our brand colors were defined in the styleguide

### PR DESCRIPTION
**Pull request by restlessbit**
Closes #173 

Adds colors defined in `variables/_colors.scss` to the styleguide.

screen shot 2016-06-14 at 5 19 15 pm

/cc @underdogio/engineering

### CODE REVIEW

**Comment by brettlangdon** [comment]
Nice.

The only thing is, do we want this to be apart of the shared styles or for this repo only?

**Comment by restlessbit** [comment]
I'm not sure I follow... but the primary use case of this section is so someone wouldn't have to dig into the source code to get a hex value for one of our branding colors.

**Comment by brettlangdon** [comment]
What I am saying is, as-is these new styles `color-block` will be included in the bundle for our other applications, when it `color-block` isn't a organization wide style, a `underdog-styles` specific thing.

**Comment by restlessbit** [comment]
Ahhhh okay. We can create a separate bundle for styles that are intended just for the styleguide.

**Comment by brettlangdon** [comment]
:+1:

**Comment by restlessbit** [comment]
I updated our `build-sass` script to build any non-partial (doesn't start with an underscore) Sass file in the root of the `/scss` directory, and created a new directory for the regular `underdog` bundle and the new `styleguide` bundle.

**Comment by brettlangdon** [comment]
lgtm

**Pull request merged**
