### PR TITLE
Declare inuit.css to be a peer dependency

### PR DESCRIPTION
**Pull request by restlessbit**
This is required until we can upgrade to a version of npm that flattens dependencies :/ 

womp womp 

/cc @underdogio/engineering

### CODE REVIEW

**Comment by brettlangdon** [comment]
lgtm after tests pass

**Comment by restlessbit** [comment]
This isn't going to work. I guess we're just going to wait until we get dependency flattening :/

**Comment by brettlangdon** [comment]
wait, why isn't this going to work?

**Comment by restlessbit** [comment]
If `inuit.css` is a peer dependency, then it won't be installed when running `npm install`. If `inuit.css` is a regular dependency and a peer dependency, npm complains about peer dependencies not being present when installing.

**Comment by brettlangdon** [comment]
that is... interesting...

**Pull request closed without merging**
