### PR TITLE
Add scripts for creating icon fonts

### PR DESCRIPTION
**Pull request by restlessbit**
Adds some scripts so we can automagically create our icon fonts instead of having to use Icomoon. Yay!

There is one small downside to this approach, which is that we have to make sure all of our icons are the same size now; I tried using the `--normalize` feature of `svgicons2svgfont` but it didn't seam to work. I made a note of this in the README.

Also since all icons are now the same size, there are a few cases where the sizes of some icons increased (like 'arrow')

*Before*

before

*After*

after

We can mark the next release as a minor update so we can remember to apply the `.icon--small` modifier to icons that look too big in our projects.

/cc @underdogio/engineering

### CODE REVIEW

**Comment by brettlangdon** [comment]
The `user` logo is not rendered above.

**Comment by brettlangdon** [comment]
Also, it doesn't seem like all the icons are centered, this also seems to be a problem with the old icons as well, but not sure if that is something we care about, them all being center aligned, so they take up the same width and have the same whitespace when being rendered

**Comment by brettlangdon** [comment]
Sorry... accidentally closed the PR :(

**Comment by restlessbit** [comment]
Yeah I'm not sure what the deal is with the user icon. But we were never using it so ¯\_(ツ)_/¯

Not sure why some icons have different widths... maybe because they have extra whitespace around them?

**Pull request merged**
