### PR TITLE
 Add case study block component

### LINKED ISSUE #254: Case study block component
screen shot 2016-08-15 at 1 47 11 pm

### PR DESCRIPTION
**Pull request by restlessbit**
Closes #254 

Adds this thing:

*Wide*

wide

*Narrow*

narrow

/cc @underdogio/engineering @cmuir

### CODE REVIEW

**Comment by cmuir** [comment]
Looks really awesome. Might be the best thing we've ever done together.

**Comment by cmuir** [comment]
🎉

**Comment by restlessbit** [comment]
for real. except maybe not better than being the only ones on the team who were brave enough to ride the Thunderbolt 😎

**Comment by brettlangdon** [comment]
lgtm

**Pull request merged**
